format_version: 10
pipelines:
  test-hello-world:
    group: defaultGroup
    label_template: ${COUNT}
    lock_behavior: unlockWhenFinished
    display_order: -1
    materials:
      git-b0e531f:
        git: https://github.com/cargillchantry/hello-world
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - Build-And-Test:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: success
            allow_only_on_success: false
          jobs:
            Clean-Build:
              timeout: 0
              artifacts:
                - build:
                    source: build/libs/*
                    destination: build/libs/
              tasks:
                - exec:
                    arguments:
                      - clean
                      - build
                    command: gradle
                    run_if: passed
      - Publish:
          fetch_materials: true
          keep_artifacts: false
          clean_workspace: false
          approval:
            type: manual
            allow_only_on_success: true
          jobs:
            Create-Image-And-Publish:
              timeout: 0
              artifacts:
                - external:
                    id: hello-world
                    store_id: chantry
                    configuration:
                      options:
                        BuildFile: 'hello-world.json'
              tasks:
                - fetch:
                    is_file: false
                    source: build/libs/
                    destination: build/
                    pipeline: test-hello-world
                    stage: Build-And-Test
                    job: Clean-Build
                    artifact_origin: gocd
                    run_if: passed
                - exec:
                    arguments:
                      - -c
                      - docker build --tag chantry.jfrog.io/experiment-docker/hello-world:$(ls build/libs | head -n 1 | sed "s/hello-world-//g" | sed "s/-.*//g") .
                    command: /bin/bash
                    run_if: passed
                - exec:
                    arguments:
                      - -c
                      - >-
                        echo '{"image": "chantry.jfrog.io/experiment-docker/hello-world", "tag": "TAG"}' | sed "s/TAG/$(ls build/libs | head -n 1 | sed "s/hello-world-//g" | sed "s/-.*//g")/g" > hello-world.json
                    command: /bin/bash
                    run_if: passed